### ISSUE TITLE
Revisão geral das entregas

### ISSUE THREAD

**Issue by pedrobarbosaocb** [Requisitos-de-Software/2023.1-Caesb#87]
# Descrição
- Na reunião 04 (#86), foi discutido sobre os pontos de correção de todas as entregas. Com isso, estou juntando nessa issue todas as correções que devem ser feitas. Assim que terminá-as, marque a checkbox.

# Correções por nome
#### PLANEJAMENTO - Aplicativo escolhido
- [x] Centralizar tabelas e imagens
- [x] Corrigir Bibliografia
- [x] Rever os tópicos (barra lateral)

#### ELICITAÇÃO - Perfil de usuário
- [ ] Adicionar atitudes do usuário (tecnófilos, tecnófobos)
- [ ] Reduzir a introdução
- [ ] Trocar a palavra imagem por figura na legenda
- [ ] Chamar as figuras no texto
- [ ] Trocar referência por bibliografia
- [ ] Verificar gravação e registros da elicitação dos requisitos

#### ELICITAÇÃO - Personas
- [ ] Corrigir pontuação dos tópicos
- [ ] Trocar a palavra imagem por figura na legenda
- [ ] Chamar as figuras e as tabelas no texto
- [ ] Trocar referência por bibliografia 
- [ ] Reduzir o histórico de versão
- [ ] Apresentar na citação de Courage e Baxter, o que eles falam e quem são essas pessoas referenciadas.

#### Ferramentas
- [x] Centralizar tabelas
- [x] Trocar referência por bibliografia
- [x] Reduzir a tabela de versionamento

#### Introspecção
- [ ] Trocar referência por bibliografia
- [ ] Adicionar requisitos que faltam (presentes nas três últimas linhas do backlog)
- [ ] Verificar gravação e registros da elicitação dos requisitos

#### Casos de Uso
- [ ] Adicionar os participantes e papel (usuário, personas, Eng. de Requisitos ect), técnicas utilizadas, Local/data/horário da especificação do cenários para o projeto.

#### PLANEJAMENTO - Metodologia
- [ ] Adicionar legenda no código
- [ ] Centralizar tabela
- [ ] Trocar referência por bibliografia

#### RASTREABILIDADE - Pré-Rastreabilidade
- [ ] Reduzir o título para escolha do aplicativo
- [ ] Tirar todos e colocar nome de cada integrante
- [ ] Trocar referência por bibliografia

#### ELICITAÇÃO - Storytelling
- [ ] TÍTULO DO STORYTELLING
- [ ] Revisar escrita nos textos
- [ ] Rever os títulos (barra lateral - ### )
- [ ] Ajustar o padrão da bibliografia
- [ ] Ajustar a tabela de revisão (data e esta quebrada)
- [ ] A gravação e registros da elicitação dos requisitos
- [ ] Aprofundar requisitos para poderem ser testados

#### MODELAGEM - Cenários
- [ ] Ajustar pontuação dos tópicos (; e . no final)
- [ ] Padronizar tópicos dentro da tabela
- [ ] Ajustar bibliografia
- [ ] Rordenar a barra lateral em ordem alfabética 
- [ ] Adicionar os participantes e papel (usuário, personas, Eng. de Requisitos ect), técnicas utilizadas, Local/data/horário da especificação do cenários para o projeto.

#### MODELAGEM ÁGIL - Histórias de Usuário
- [ ] Colocar o texto de Introdução como primeiro item do artefato
- [ ] Centralizar tabela
- [ ] Tiras os : nos títulos
- [ ] Destacar os motivos (negrito no tópico)
- [ ] Refinar histórias de usuário dos subtítulos (ex: Modelo de História de Usuário -> Modelo)
- [ ] Destacar critérios de prioridade
- [ ] Padronizar os traços de tópicos
- [ ] Explicar no texto o que é a sigla US
- [ ] Ajustar histórico de versão

#### PLANEJAMENTO - Cronograma de Planejamento
- [ ] Tirar a palavra todos e colocar o nome de cada integrantes
- [ ] Título da introdução
- [ ] Tirar a carla na parte de integrante responsável
- [ ] Citar as tabelas no texto
- [ ] Mudar os #### de entregas
- [ ] Trocar referência por bibliografia

#### MODELAGEM ÁGIL - Backlog
- [ ] Adicionar requisitos na introspecção

#### ATAS e GUIA 
- [ ] Mudar modelo/padronização
- [ ] Iframe dos vídeos

#### HOME e GITPAGE
- [x] Add Bibliografia
- [x] Integrantes: Tirar a carla, centralizar tabela

#### ELICITAÇÃO - Priorização
- [x] Juntar as duas priorizações em um documento só
- [ ] A participação de personas na priorização de requisitos (através da técnica de encenação
- [x] Um cronograma (data e horário) e local para realização da elicitação dos requisitos com o do cliente e/ou persona do projeto?
- [ ] Um cronograma (data e horário) e local para realização da priorização dos requisitos com o do cliente e/ou persona do projeto?
- [ ] Se possível, acrescentar a priorização dos requisitos elicitados que vão acrescentar

#### MODELAGEM - Léxicos
- [x] A definição do usuário nos Léxicos?
- [x] Ajustar bibliografia
- [x] Centralizar tabelas
- [x] Barra lateral em ordem alfabética 

--- 
# Dúvidas?
- Qualquer dúvida/dores/discordâncias comente nessa issue, ou nos contate pelo grupo do Telegram.

**Comment by caeslucio** [comment]
## [Caetano](@caeslucio)
#### PLANEJAMENTO - Heatmap
- [ ] **Artefato de Verificação** 
- [ ] Chamar a tabela e centralizar
- [ ] Trocar referência por bibliografia

#### MODELAGEM ÁGIL - NFR
- [ ] **Artefato de Verificação**
- [ ] Destacar os tópicos de softgoals
- [ ] Chamar a figuras no texto
- [ ] Correção ortográfica das contribuições
- [ ] Ajustar os ### (subtitulos e barra lateral)
- [ ] Adicionar SIG conforme especificação suplementar
- [ ] Mudar a fonte para o autor do texto

#### PLANEJAMENTO - Cronograma Realizado
- [ ] **Artefato de Verificação**
- [ ] Adicionar texto de introdução...
- [ ] ctrl+v cronograma planejado

#### ELICITAÇÃO - Questionário
- [ ] **Artefato de Verificação**
- [ ] Refinar o texto de introdução em metodologia
- [ ] Ajustar a legenda e chamar a tabela no texto
- [ ] Trocar referência por bibliografia
- [ ] Verificar gravação e registros da elicitação dos requisitos
- [ ] Aprofundar requisitos para poderem ser testados

#### APRESENTAÇÃO
- [ ] **Artefato de Verificação**
- [ ] Trocar link por Iframe
- [ ] Trocar a palavra todos pelo nome de cada integrante
- [ ] Reduzir versionamento
